/**
 * This file was generated by `pnpm gen:api` (scripts/gen-api.mjs). Do not edit it by hand.
 * See docs/tipos-de-la-api.md.
 */
export interface paths {
    "/actuator/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Salud mínima del servicio
         * @description Público. No revela detalles internos.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta/constraints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Límites de campos para armar los formularios
         * @description Público. Cada clave es un campo (por ejemplo reading.note) con sus límites tomados de FieldLimits en el backend.
         */
        get: operations["getConstraints"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorBody: {
            /**
             * @description Código en SCREAMING_SNAKE_CASE del catálogo de API.md sección 1.4.
             * @example GAUGE_OUT_OF_RANGE
             */
            code: string;
            /** @description Mensaje en español. Sirve de respaldo; la UI usa el texto de es.ts. */
            message: string;
            /** @description Objeto opcional con datos del error. Sin trazas ni secretos. */
            details?: {
                [key: string]: unknown;
            };
            /** @description Correlaciona la respuesta con los registros. También viene en X-Request-Id. */
            request_id: string;
        };
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        HealthResponse: {
            /** @enum {string} */
            status: "UP" | "DOWN";
        };
        /** @description Límites de un campo. Todos son opcionales: solo llegan los que aplican. */
        FieldConstraint: {
            /** Format: int32 */
            min?: number;
            /** Format: int32 */
            max?: number;
            /** @description Expresión regular compatible con JavaScript (bandera u). */
            pattern?: string;
            /** Format: int32 */
            max_lines?: number;
        };
        /** @description Mapa plano de nombre de campo a límites (API.md sección 4.1). */
        ConstraintsResponse: {
            [key: string]: components["schemas"]["FieldConstraint"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description El servicio responde. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description El servicio no está disponible. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getConstraints: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Mapa campo a límites. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConstraintsResponse"];
                };
            };
            /** @description Demasiadas solicitudes (RATE_LIMITED). */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error no controlado (INTERNAL_ERROR). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
