// Generates src/services/api/schema.d.ts from the OpenAPI document of the backend.
//
// Source, in order of preference:
//   1. The path or URL given as the first argument.
//   2. A backend snapshot: OPENAPI_SNAPSHOT, or caudal-backend/docs/openapi.json next to this repo.
//   3. The live backend, when VITE_API_BASE_URL is set in the environment:
//      <origin of VITE_API_BASE_URL>/v3/api-docs.
//   4. docs/openapi.json of this repo (minimal snapshot).
//
// Flags: --check compares the result with the committed file and fails on any difference.
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

import openapiTS, { astToString } from 'openapi-typescript';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUTPUT = resolve(root, 'src/services/api/schema.d.ts');
const REPO_SNAPSHOT = resolve(root, 'docs/openapi.json');
const API_DOCS_PATH = '/v3/api-docs';
const BACKEND_SNAPSHOT_CANDIDATES = [
  resolve(root, '../caudal-backend/docs/openapi.json'),
  resolve(root, '../../caudal-backend/docs/openapi.json'),
];
const HEADER = [
  '/**',
  ' * This file was generated by `pnpm gen:api` (scripts/gen-api.mjs). Do not edit it by hand.',
  ' * See docs/tipos-de-la-api.md.',
  ' */',
  '',
].join('\n');

function isUrl(value) {
  return /^https?:\/\//.test(value);
}

function resolveSource(argument) {
  if (argument !== undefined) {
    return isUrl(argument) ? argument : resolve(process.cwd(), argument);
  }
  const snapshot = [process.env.OPENAPI_SNAPSHOT, ...BACKEND_SNAPSHOT_CANDIDATES].find(
    (candidate) => candidate !== undefined && candidate !== '' && existsSync(candidate),
  );
  if (snapshot !== undefined) {
    return snapshot;
  }
  const apiBase = process.env.VITE_API_BASE_URL;
  if (apiBase !== undefined && apiBase !== '') {
    return `${new URL(apiBase).origin}${API_DOCS_PATH}`;
  }
  return REPO_SNAPSHOT;
}

const ARGUMENTS_TO_SKIP = 2; // node binary and script path
const args = process.argv.slice(ARGUMENTS_TO_SKIP);
const check = args.includes('--check');
const source = resolveSource(args.find((arg) => !arg.startsWith('--')));
console.log(`OpenAPI source: ${source}`);

const input = isUrl(source) ? new URL(source) : pathToFileURL(source);
const ast = await openapiTS(input);
const generated = `${HEADER}${astToString(ast)}`;

if (check) {
  const current = existsSync(OUTPUT) ? readFileSync(OUTPUT, 'utf8') : '';
  if (current !== generated) {
    console.error('src/services/api/schema.d.ts is out of date. Run `pnpm gen:api`.');
    process.exit(1);
  }
  console.log('src/services/api/schema.d.ts is up to date.');
} else {
  writeFileSync(OUTPUT, generated);
  console.log(`Written ${OUTPUT}`);
}
